services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: .env
