"""empty message

Revision ID: 8a21bebfaf86
Revises: 
Create Date: 2024-09-27 04:49:28.932380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a21bebfaf86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('max_session_duration', sa.Interval(), nullable=False),
    sa.Column('available_time_start', sa.Time(), nullable=False),
    sa.Column('available_time_end', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE ('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE ('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=False),
    sa.Column('schedule_type', sa.Enum('sole', 'weekday', 'monthly', 'monthly_weekday', name='scheduletype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.Time(), nullable=False),
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE ('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE ('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_rules_doctor_id'), 'appointment_rules', ['doctor_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_rule_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_rule_id'], ['appointment_rules.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_appointment_rules_doctor_id'), table_name='appointment_rules')
    op.drop_table('appointment_rules')
    op.drop_table('doctors')
    # ### end Alembic commands ###
